version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/wangrui/Desktop/project/personal-sql⁠
    environment:
      MYSQL_DATABASE: personal-back
      MYSQL_ROOT_PASSWORD: wang
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/wangrui/Desktop/project/personal-redis
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
